# -*- coding: utf-8 -*-
"""projeto-algoritmo-de-auditoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc0s-PHTd3IBWP06eNZpkD7bzGk89qgF
"""

LIMITE_SEGURANCA = 10000

venda1 = float(input("Digite o valor da primeira venda: "))
venda2 = float(input("Digite o valor da segunda venda: "))

venda3 = float(input("Digite o valor da terceira venda: "))



def analisar_vendas():

  global LIMITE_SEGURANCA

  soma = venda1 + venda2 + venda3

  media = soma / 3 # Definindo a variável media novamente



  print (f"O valor médio de vendas é: {media:.2f}")



  if media >= LIMITE_SEGURANCA:

    print (f"SISTEMA EM QUARENTENA!")

    resposta_gerente = input("Gerente, deseja aumentar o limite para liberar o sistema? (s/n): ")

  if resposta_gerente.lower() == 's':

   LIMITE_SEGURANCA = float(input("Novo valor do limite: "))

   print(f"Limite atualizado para {LIMITE_SEGURANCA}. Sistema liberado.")



  if venda1 >= media * 5:
    print (f"REVISÃO MANUAL: ({venda1:.2f}) ")
  if venda2 >= media * 5:
    print (f"REVISÃO MANUAL: ({venda2:.2f})")
  if venda3 >= media * 5:
    print (f"REVISÃO MANUAL: ({venda3:.2f})")

analisar_vendas()